/**
 * IImsQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.cm.dk.ws.imsqueryservice;

public interface IImsQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryPayChannelResponse2 doQueryPayChannel2(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, java.lang.Long acctId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQuerySharingPromotionResponse do_querySharingPromotion(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQuerySharePromReq querySharePromReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryDDFeeResponse doQueryDDFee(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryDDFeeReq SQueryDDFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryGroupInfoResponse do_queryGroupInfo(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryGroupReq sQueryGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryMaxFreeResourceResponse doQueryMaxFreeResource(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryMaxFreeResourceReq queryMaxFreeResourceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryPCRFInfoResponse doQueryPCRFInfo(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryPCRFInfoReq doQueryPCRFInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.AcctStatusResponse doQueryAcctStatus(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.AcctStatusParamReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryPayChannelResponse doQueryPayChannel(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, java.lang.Long acctId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryVpnNumberResponse do_queryVpnNumber(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryVpnNumberReq sQueryVpnNumberReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryUsersByBssResponse do_queryUsersByBssbroker(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryUsersByBssReq sQueryUsersByBssReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryBusiSuccessResponse do_queryBusiSuccess(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.QueryBusiSuccessReq qryBusiSuccess) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.SUnOrderProductFeeResponse doQueryUnOrderProductFee(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SOrderProductFeeRequest requestBody) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.SOrderProductFeeResponse doQueryOrderProductFee(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SOrderProductFeeRequest requestBody) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryNotifyFlagResponse doQueryNotificationFlag(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryNotifyFlagReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryProdStateResponse do_queryProdState(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryProdState req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryGroupMembersResponse do_queryGroupMembers(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.QueryGroupMembersReq queryGroupMembersReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.QueryBillDetailResponse doQueryBillDetail(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryBillDetailReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryProdCycleInfoResponse doQueryProdCycleInfo(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryProdCycleInfoReq doQueryProdCycleInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoNetaxeptQueryResponse doNetaxeptQuery(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoNetaxeptQueryReq doNetaxeptQueryReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryServiceStateResponse do_queryServiceState(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQuerySrvStateReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryMemberInfoResponse do_queryMemberInfo(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryGroupMemberReq sQueryGroupMemberReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQuerySuppressNotificationResponse do_querySuppressNotification(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQuerySuppressNotificationReq querySuppressNotificationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryFNResponse do_queryFN(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.QueryFnReq queryFnReq, com.asiainfo.crm.cm.dk.ws.imsqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryScpProfileResponse do_queryScpProfile(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.ScpProfileReq scpProfileReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryPayChannelHisResponse doQueryPayChannelHis(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryPaychannelHisReq queryPayChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryCallScreenResponse do_queryCallScreen(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.QueryCallScreenReq queryCallScreenReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.QueryPbsManualResponse doQueryPbsManualData(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SearchPbsManualForm searchPbsManualReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQryExemptionResponse do_qryExemption(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.QryExemptionReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsqueryservice.DoQueryProductBillAttrResponse doQueryProductBillAttr(com.asiainfo.crm.cm.dk.ws.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsqueryservice.SQueryProductBillAttrReq req) throws java.rmi.RemoteException;
}
