/**
 * IImsServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.so.exe.ws.crmcallams.imsservice;

public interface IImsServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoSetConsumptionResponse doSetConsumption(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SSetConsumptionReq sSetBudget) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoRemoveUserResponse do_removeUser(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SRemoveReq sRemove, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoManagePayChannelResponse doManagePayChannel(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ManagePayChannelReq managePayChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoSetNotificationFlagResponse doSetNotificationFlag(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SSetNotificationFlagReq ssetNotificationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeProductResponse do_changeMainPromotion(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SChangeProduct sChgProduct, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoCancelProductAuthResponse doCancelProductAuth(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoCancelProductAuthReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ChgGroupProductResp do_changeGroupProducts(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ChgGroupProduct sChangeInfo, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNetaxeptRegisterResponse doNetaxeptRegister(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNetaxeptRegisterReq doNetaxeptRegisterReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoModifyAccountBasicInfoResponse doModifyAccountBasicInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SAccount sAccount, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SContactOper[] sContactOperList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNewRegistrationResponse doNewRegistration(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.NewRegistration newRegistration, java.lang.Short flag, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoModifyCustBasicInfoResponse do_modifyCustBasicInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SCustomer sCustomer, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SContactOper[] sContactOperList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoDeleteGroupResponse do_deleteGroup(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SDeleteGroupReq sDeleteGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoProductAuthResponse doProductAuth(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoProductAuthReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoCaRelationResponse do_caRelation(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ScaRelateReq sCARelationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNPRangeSyncResponse doNPRangeSync(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.NpRangeInfo[] doNPRangeSyncReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoCaRelationUserResponse do_caRelationUser(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ScaRelateUserReq sCARelationUserReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoRenewRegistrationResponse do_renewRegistration(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RenewRegistration sRenew) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangePaymentModeResponse do_changePaymentMode(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SChangePaymentModeReq sChangePaymentMode, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoDeactivateGroupResponse do_deactivateGroup(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SDeactivateGroupReq sDeactivateGroupReq) throws java.rmi.RemoteException;
    public void do_UpdateBillingAddressInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SBillingAddressInfo billingAddressInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoMgntCallScreenResponse do_mgntCallScreen(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SMgntCallScreenReq sCallScreenReq, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeOwnerReqResponse do_changeOwnerReq(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SChangeOwnerReq sChangeOwner, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeMsisdnAndSimResponse do_changeMsisdnAndSim(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ChangeMsisdnAndSimInfo changeInfo, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNetaxeptProcessResponse doNetaxeptProcess(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNetaxeptProcessReq doNetaxeptProcessReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoSetExemptCreditLimitResponse doSetExemptCreditLimit(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SSetEmptLimitReq setExemptLimitReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoSetBudgetResponse doSetBudget(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SSetBudgetReq sSetBudget) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoBankConfigurationResponse do_bankConfiguration(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.BankInfo bankInfo, java.lang.Short oper_type) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoDeletePrematchResponse do_deletePrematch(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SDeletePrematchReq sDeletePrematchReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoCreditNotifyMgntResponse doManageNotifyFlag(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SCreditNotifyMgntReq sCreditNotifyMgntReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoLifeCycleMgntResponse doLifeCycleMgnt(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SUserStatus sLifeCycle, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoRequestBodResponse doRequestBod(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SRequestBodReq sRequestBodReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeProductResponse do_changeProduct(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SChangeProduct sChgProduct, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoMgntCRMBlackListResponse do_mgntCRMBlackList(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SMgntCRMBlackListReq smgntCRMBlackListReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoReguideMgntResponse do_reguide(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SUserPayReguideRel[] sRelationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeUserLanguageResponse do_changeUserLanguage(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ChangeUserLanguageReq changeUserLanguageReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoSetMaxFreeResourceResponse doSetMaxFreeResource(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.MaxFreeResourceReq maxFreeResourceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoSplitResponse do_split(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SUserPaySplitRel[] relationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoModifyProductStateResponse do_modifyProductState(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ModifyProductState sChangeInfo, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee sOneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoVPNGroupRelationResponse do_vpnGroupRelation(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SvpnRelationReq SVPNRelationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoMgntGroupMemberResponse do_mgntGroupMember(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SMgnGroupMemberReq sMngGroupMemberReq, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoOperateMultiSimResponse do_manageMultiSim(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SOperateMultiSimReq sOperateMultiSimReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoFirstActivationResponse do_firstActivation(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SFristActiveReq sFristActiveReq, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoOrderProductAuthReq doOrderProductAuth(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoOrderProductAuthResponse req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoDismissReqResponse do_dismissReq(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SDismissReq sDismissReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoManageUserFriendsNumsResponse do_manageUserFriendsNums(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ManageUserFriendsNum sMangeUserFNs, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeBillCycleResponse do_changeBillCycle(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SChgBillCycleReq sChgBillCycleReq, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SBillCycle old_bill_cycle, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SBillCycle new_bill_cycle, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoManageIRPartyResponse do_manageIRParty(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SManagerIRPartyReq sManageIRParty) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeGroupResponse do_changeGroup(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SGroup sGroup) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoAuthParentResponse do_authParent(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SAuthParentReq sAuthReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoModifyUserBasicInfoResponse do_modifyUserBasicInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SUser sUser) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoDeactivateGroupMemResponse do_deactivateGroupMem(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SDeactivateGroupMemReq sDeactivateGroupMemReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoResetNegativeValueResponse do_resetNegativeValue(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SResetNegativeValueReq resetNegativeValueReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNumberPortabilityResponse doNumberPortability(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.MnpReq[] mnpList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoMgntScpProfileResponse do_mgntScpProfile(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.ScpProfileInfo scpProfileInfo, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SUserAuth sUserAuth, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoNewGroupReqResponse do_newGroupReq(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SNewGroupReq sNewGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.DoChangeGroupInfoResponse do_changeGroupInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsservice.SChangeGroupInfoReq changeGroupInfoReq) throws java.rmi.RemoteException;
}
