/**
 * IImsQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis #axisVersion# #today# WSDL2Java emitter.
 */

package com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice;

public interface IImsQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryPayChannelResponse2 doQueryPayChannel2(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, java.lang.Long acctId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQuerySharingPromotionResponse do_querySharingPromotion(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQuerySharePromReq querySharePromReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryDDFeeResponse doQueryDDFee(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryDDFeeReq SQueryDDFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryGroupInfoResponse do_queryGroupInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryGroupReq sQueryGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryMaxFreeResourceResponse doQueryMaxFreeResource(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryMaxFreeResourceReq queryMaxFreeResourceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryPCRFInfoResponse doQueryPCRFInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryPCRFInfoReq doQueryPCRFInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.AcctStatusResponse doQueryAcctStatus(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.AcctStatusParamReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryPayChannelResponse doQueryPayChannel(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, java.lang.Long acctId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryVpnNumberResponse do_queryVpnNumber(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryVpnNumberReq sQueryVpnNumberReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryUsersByBssResponse do_queryUsersByBssbroker(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryUsersByBssReq sQueryUsersByBssReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryBusiSuccessResponse do_queryBusiSuccess(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.QueryBusiSuccessReq qryBusiSuccess) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SUnOrderProductFeeResponse doQueryUnOrderProductFee(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SOrderProductFeeRequest requestBody) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SOrderProductFeeResponse doQueryOrderProductFee(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SOrderProductFeeRequest requestBody) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryNotifyFlagResponse doQueryNotificationFlag(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryNotifyFlagReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryProdStateResponse do_queryProdState(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryProdState req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryGroupMembersResponse do_queryGroupMembers(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.QueryGroupMembersReq queryGroupMembersReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.QueryBillDetailResponse doQueryBillDetail(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryBillDetailReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryProdCycleInfoResponse doQueryProdCycleInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryProdCycleInfoReq doQueryProdCycleInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoNetaxeptQueryResponse doNetaxeptQuery(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoNetaxeptQueryReq doNetaxeptQueryReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryServiceStateResponse do_queryServiceState(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQuerySrvStateReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.UpdatePayChannelResponse updatePayChannel(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.UpdatePayChannelReq payChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryMemberInfoResponse do_queryMemberInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryGroupMemberReq sQueryGroupMemberReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQuerySuppressNotificationResponse do_querySuppressNotification(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQuerySuppressNotificationReq querySuppressNotificationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryFNResponse do_queryFN(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.QueryFnReq queryFnReq, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryScpProfileResponse do_queryScpProfile(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.ScpProfileReq scpProfileReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryCallScreenResponse do_queryCallScreen(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.QueryCallScreenReq queryCallScreenReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryPayChannelHisResponse doQueryPayChannelHis(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryPaychannelHisReq queryPayChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQryExemptionResponse do_qryExemption(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.QryExemptionReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.DoQueryProductBillAttrResponse doQueryProductBillAttr(com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imsqueryservice.SQueryProductBillAttrReq req) throws java.rmi.RemoteException;
}
