/**
 * IImsQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice;

public interface IImsQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQuerySharingPromotionResponse do_querySharingPromotion(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQuerySharePromReq querySharePromReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryDDFeeResponse doQueryDDFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryDDFeeReq SQueryDDFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryGroupInfoResponse do_queryGroupInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryGroupReq sQueryGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryMaxFreeResourceResponse doQueryMaxFreeResource(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryMaxFreeResourceReq queryMaxFreeResourceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPCRFInfoResponse doQueryPCRFInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPCRFInfoReq doQueryPCRFInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.AcctStatusResponse doQueryAcctStatus(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.AcctStatusParamReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPayChannelResponse doQueryPayChannel(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, java.lang.Long acctId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryVpnNumberResponse do_queryVpnNumber(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryVpnNumberReq sQueryVpnNumberReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryUsersByBssResponse do_queryUsersByBssbroker(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryUsersByBssReq sQueryUsersByBssReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryBusiSuccessResponse do_queryBusiSuccess(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryBusiSuccessReq qryBusiSuccess) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryNotifyFlagResponse doQueryNotificationFlag(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryNotifyFlagReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryProdStateResponse do_queryProdState(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryProdState req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryGroupMembersResponse do_queryGroupMembers(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryGroupMembersReq queryGroupMembersReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryBillDetailResponse doQueryBillDetail(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryBillDetailReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryProdCycleInfoResponse doQueryProdCycleInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryProdCycleInfoReq doQueryProdCycleInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoNetaxeptQueryResponse doNetaxeptQuery(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoNetaxeptQueryReq doNetaxeptQueryReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryServiceStateResponse do_queryServiceState(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQuerySrvStateReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryMemberInfoResponse do_queryMemberInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryGroupMemberReq sQueryGroupMemberReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQuerySuppressNotificationResponse do_querySuppressNotification(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQuerySuppressNotificationReq querySuppressNotificationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryFNResponse do_queryFN(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryFnReq queryFnReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryScpProfileResponse do_queryScpProfile(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.ScpProfileReq scpProfileReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryCallScreenResponse do_queryCallScreen(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryCallScreenReq queryCallScreenReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPayChannelHisResponse doQueryPayChannelHis(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPaychannelHisReq queryPayChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQryExemptionResponse do_qryExemption(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QryExemptionReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryProductBillAttrResponse doQueryProductBillAttr(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryProductBillAttrReq req) throws java.rmi.RemoteException;
}
