/**
 * IImsWrapQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice;

public interface IImsWrapQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryAllowanceResponse doQueryAllowance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAllowanceReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryTemplateResponse doQueryTemplate(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryTemplateReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryInvoiceAttributeResponse doQueryInvoiceAttribute(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryInvoiceAttributeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryReguideInfoResp do_queryReguideInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryReguideReq queryReguideReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAllowanceDtlResp doQueryAllowanceDtls(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAllowanceDtlReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryCDRSumResponse doQueryCDRSum(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryCDRSumReq sQueryCDRSumReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryThrottledResp doQueryThrottled(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryThrottledReq sQueryThrottledReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryInvoiceInfoResponse do_queryInvoiceInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryInvoiceInfoReq sQueryInvoiceInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryInstallmenInfoResponse doQueryInstallmentInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryInstallmentInfoReq SQueryInstallmentInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryTransactionfeeResp doQueryTransactionFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryTransactionFeeReq queryTransactionFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryAcctInfoForPayResponse doQueryAcctInfoForPay(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryAcctInfoForPayReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryOrderInfoResponse doQueryOrderInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryOrderInfoReq doqueryOrderInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.Billinfo[] do_queryBillExt(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryBillExt sQueryBillExtReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryBillingStatusResponse do_queryBillingStatus(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQryBillStsReq qryBillStsReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryMainPhoneByAcctIdResponse do_queryMainPhoneByAcctId(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryMainPhoneByAcctIdReq queryMainPhoneByAcctIdReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryMdbDataResponse do_queryAbmData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryAbmDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAcctDetailByCustResponse doQueryAcctDetailByCust(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAcctDetailByCustReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryWorkLogResponse doQueryWorkLog(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryWorkLogReq queryWorkLogReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryGraphResponse do_queryGraph(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryGraphReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryBillExResponse doQueryBillEx(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QryBillForOSEInReq qryBillForOSEInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.OrderInfoResp doQueryUnifiedPay(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.OrderInfoReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryProductChargeResponse doQueryProductCharge(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQryProdChargeIn[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAgentBalanceResponse doQueryAgentBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAgentBalanceReq doQueryAgentBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.GetDebitDataResponse doQueryDebitData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.GetDebitDataRequest req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.BillAmountResponse doQueryBillAmount(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryBillAmountParam queryBillAmountParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryTermBalanceResponse doQueryTermBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.TermQueryParam termQueryParam, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoGetCaInvIndexResponse doGetCaInvIndex(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SgetCaInvIndexReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoSMngQueryDepositResponse doQueryDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SMngQueryDepositReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryCapMaxResponse do_queryCapMax(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryCapMaxReq sQueryCapMaxReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryLostBalanceResponce do_queryLostBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryLostBalanceReq queryLostBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.BillAmountResponse doQueryBillAmountByType(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryBillAmountReq queryBillAmountReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPayInfoResponse doQueryPayInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryPayInfoReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAgentDepositResponse doQueryAgentDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAgentDepositReq doQueryAgentDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryRegretDeductInfoResponse doQueryRegretDeductInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryRegretInfo queryRegretInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryNotifyHisResponse doQueryNotifyHis(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryNotificationHisReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryNtCdrResponse do_queryNtCdr(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryNtCdrReq sQueryNtCdrReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryRecurringfeeOnetimefeeResp doQueryRecurringAndOnetimeFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryRecurringAndOnetimeFeeReq queryRecurringFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryRegretStsResponse doQueryRegretSts(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryRegretInfo queryRegretInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryCDRBusiResp doNewQueryCDRBusi(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryCDRBusiReq sQueryCDRBusiReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAcctStatusmentResp doQueryAccountStatement(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAcctStatusmentReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryResponse doQuery(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryType[] queryTypeList, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAutoTopUpResponse do_queryAutoTopUp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryAutoTopUpReq queryAutoTopUpReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public void do_clearDbAndMdbData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.ClearDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryCDRResponse doQueryCDR(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryCDRReq sQueryCDRReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryLedgerResponse doQueryLedger(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryledgerInReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAmountResp doQueryAmount(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryAmountReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryDeductCondResponse doQueryDeductCond(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryDeductCondRequest req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryTaxResponse doQueryTax(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryTaxReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryBillXmlResponse doQueryBillXml(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryBillXmlReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.STransferTransformRuleResponse doQueryTransferTransformRule(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.STransferTransformRuleReq requestBody) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryCDRFileResponse doQueryCDRFile(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryCDRReq sQueryCDRReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryAccountInfoResponse do_QueryAccountInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.QueryType[] queryTypeList, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryAccountInfoParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryMdbDataResponse do_queryMdbData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQueryMdbDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.DoQueryPointInfoResponse doQueryPoint(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.SQryPointInfoReq SQryPointInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.FreeResInfoResp doQueryFreeResInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, long[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.TariffResInfoResp doQueryTariffInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapqueryservice.TariffResInfoReq req) throws java.rmi.RemoteException;

}
