/**
 * IImsWrapServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice;

public interface IImsWrapServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAutoTopUpResponse doAutoTopUp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SAutoTopUpReq autoTopUpReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoRegretFeeResponse doRegretFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SRegretInfo sRegretInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoRegretRefundResponse doRegretRefund(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SRegretRefundReq sRegretRefundReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCheckDepositAmountResponse doCheckDepositAmount(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.CheckDepositAmountReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAgentDepositResponse doAgentDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAgentDepositReq do_agentDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoRollbackPaymentResponse doRollbackPayment(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SReceiptInfoReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelInstalmentResponse doCancelInstalment(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SCancelInstalmentReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoUionChargeRespone doUionCharge(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.UionChargeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelOneTimeFeeResponse doCancelOneTimeFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SCancelOneTimeFeeReq sCancelOneTimeFeeReq) throws java.rmi.RemoteException;
    public void doCreditLimit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SCreditLimitInReq sCreditLimitIn) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoSMngDepositResponse doManageDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SMngDepositReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryUnOrderFeeResponse doQueryUnOrderFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryUnOrderFeeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoMailGroupManageResponse do_mailGroupManage(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SMailGroupManageReq mailGroupManageReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdTransferAssetResponse doAdTransferAsset(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AdTransferParam transferParam, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoUionChargeReplyResponse doUionChargeReply(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.UionChargeReplyReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAutoTopUpOnDemondResponse do_autoTopUpOnDemond(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AutoTopUpOnDemondReq autoTopUpOnDemondReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoOneTimeFeeResponse doOneTimeFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee[] oneTimeFeeList) throws java.rmi.RemoteException;
    public void doRePaymentFtp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, java.lang.Long seqId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInstalChangeResponse doInstalChange(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SInstalChangeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.UpdateOrderUserIdResp doUpdateOrderUserId(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OrderUserInfo orderUserInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAgentSelfDepositRespone doAgentSelfDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAgentSelfDepositReq do_agentSelfDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInstanceAllowanceResponse doInstanceAllowance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SAllowanceUsage[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdvancePaymentResponse do_advancePayment(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AdvancePaymentReq advancePaymentReq, java.lang.Short notification_flag) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoEtopupResponse do_etopup(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.EtopupReq etopupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInstalMoveResponse doInstalMove(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInstalMoveReq doInstalMoveReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdjustBillResponse doAdjustBill(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, java.lang.Short adjustType, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.Billinfo billInfo, java.lang.Short notificationFlag) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoDealApproveResponseResponse doDealApproveResponse(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoDealApproveResponseReq doDealApproveResponseReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoRepairUnifiedPayResponse doRepairUnifiedPay(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SOrderRepairInfo orderRepairInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoHotBillResponse doHotBill(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SHotBillReq sHotBillReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelTopUpResponse doCancelTopUp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SCancelTopUpReq scancelTopUp) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoLetterDataResponse doLetterData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoLetterDataReq doLetterDataReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SAdjustFinesResp doAdjustFines(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SAdjustFinesReq sAdjustFinesReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAcceptInstalResponse doAcceptInstal(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAcceptInstalReq doAcceptInstalReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInstalContractResponse doContractInstal(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SDoInstalContractReq doInstalContract) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryPayDataResponse doQueryPayData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.PrintInReq printInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AdjustMultiBillResponse doAdjustMultiBill(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AdjustMultiBillInReq adjustMultiBillInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdjustBalanceResponse doAdjustBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AdjustBalanceReq adjustReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoRefundRemainBalanceResponse doRefundRemainBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RefundParam refundParam, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoSetCreditLimitResponse doSetCreditLimit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SSetCreditLimitReq SSetCreditLimit) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAutoTopUpResponse do_autoTopUp4GUI(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AutoTopUpReq autoTopUpReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SchangeOrderInfoResp doChangeFutrueOrder(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SchangeOrderInfo req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelPaymentResponse doCancelPayment(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.CancelPaymentInfo cancelPaymentInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoChangeOrderInfoResponse doChangeOrderInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SChangeOrderParam sChangeOrderParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoPaymentAndBillAdjustResponse doPaymentAndBillAdjust(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SPaymentReq spaymentReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.FreeResourceResponse doTopUpFreeResourse(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.FreeResourceReq freeResourceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoTransferResponse doTransfer(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.STransferReq sTransferReq, java.lang.Short notificationFlag, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInsertOrderInfoResponse doInsertOrderInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SOrderInfo req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdjustPointResponse doAdjustPoint(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.AdjustPointReq adjustPointReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInsertPrtRecResponse doInsertPrtRec(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SPrintIn[] printRecReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelGsmTopUpResponse do_cancelGsmTopUp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SCancelGsmTopUpReq gsmTopUp) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoOneTimeFeeResponse do_oneTimeFeeDelayCharge(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee[] oneTimeFeeList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SconfirmOrderResp doConfirmFutrueOrder(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SconfirmFutrueInfo req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoTopUpByCashResponse doTopUpByCash(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.STopUpInfo sTopUpInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoInstallmentPrePayResponse doInstallmentPrePay(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.InstallmentPrePay[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelOrderResponse doCancelOrder(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelOrderReq doCancelOrderReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoUnifiedPayResponse doUnifiedPay(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoUnifiedPayReq doUnifiedPayReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelInstalPrePayResponse doCancelInstalPrePay(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoCancelInstalPrePayReq doCancelInstalPrePayReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdjustBetweenAcctResponse doAdjustBetweenAcct(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoAdjBetweenAcctInReq doAdjBetweenAcctInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoGsmTopUpResponse do_gsmTopUp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SGsmTopUpReq gsmTopUp) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoRejectDirectDebitResponse doRejectDirectDebit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SRejectDDReq sRejectDDReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoDeductPointsResponse do_deductPoints(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SDeductPointsReq sDeductPointsReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoSetNegativeBalanceResponse doSetNegativeBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SSetNegativeBalanceReq ssetNegativeBalanceReq) throws java.rmi.RemoteException;
}
