/**
 * IImsWrapQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice;

public interface IImsWrapQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryReguideInfoResp do_queryReguideInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryReguideReq queryReguideReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryTransactionfeeResp doQueryTransactionFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryTransactionFeeReq queryTransactionFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryCapMaxResponse do_queryCapMax(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryCapMaxReq sQueryCapMaxReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.Billinfo[] do_queryBillExt(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryBillExt sQueryBillExtReq) throws java.rmi.RemoteException;
    public void do_clearDbAndMdbData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.ClearDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAgentBalanceResponse doQueryAgentBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAgentBalanceReq doQueryAgentBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAutoTopUpResponse do_queryAutoTopUp(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryAutoTopUpReq queryAutoTopUpReq, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryWorkLogResponse doQueryWorkLog(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryWorkLogReq queryWorkLogReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryBillExResponse doQueryBillEx(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QryBillForOSEInReq qryBillForOSEInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryNotifyHisResponse do_queryNotifyHis(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryNotificationHisReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoSMngQueryDepositResponse doQueryDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SMngQueryDepositReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryInvoiceAttributeResponse doQueryInvoiceAttribute(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryInvoiceAttributeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryCDRResponse doQueryCDR(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryCDRReq sQueryCDRReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryResponse doQuery(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryType[] queryTypeList, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryAccountInfoResponse do_QueryAccountInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryType[] queryTypeList, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryAccountInfoParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryTermBalanceResponse doQueryTermBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.TermQueryParam termQueryParam, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.GetDebitDataResponse doQueryDebitData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.GetDebitDataRequest getDebitDataResponse) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryNtCdrResponse do_queryNtCdr(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryNtCdrReq sQueryNtCdrReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryMdbDataResponse do_queryAbmData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryAbmDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryOrderInfoResponse doQueryOrderInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryOrderInfoReq doqueryOrderInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryFreeResourceRatingResponse doQueryFreeResourceRating(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryFreeResourceRatingReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAcctDetailByCustResponse doQueryAcctDetailByCust(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAcctDetailByCustReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoGetCaInvIndexResponse doGetCaInvIndex(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SgetCaInvIndexReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryBillingStatusResponse do_queryBillingStatus(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQryBillStsReq qryBillStsReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryUnPayFeeResponse doQueryUnPayFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryUnPayFeeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryLedgerResponse doQueryLedger(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryledgerInReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryMdbDataResponse do_queryMdbData(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryMdbDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryInstallmenInfoResponse doQueryInstallmentInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryInstallmentInfoReq SQueryInstallmentInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.BillAmountResponse doQueryBillAmount(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.QueryBillAmountParam queryBillAmountParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAgentDepositResponse doQueryAgentDeposit(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryAgentDepositReq doQueryAgentDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryGraphResponse do_queryGraph(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryGraphReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryPointInfoResponse doQueryPoint(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQryPointInfoReq SQryPointInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryRecurringfeeOnetimefeeResp doQueryRecurringAndOnetimeFee(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryRecurringAndOnetimeFeeReq queryRecurringFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryLostBalanceResponce do_queryLostBalance(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryLostBalanceReq queryLostBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryInvoiceInfoResponse do_queryInvoiceInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryInvoiceInfoReq sQueryInvoiceInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.DoQueryPayInfoResponse doQueryPayInfo(com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.RequestHead requestHead, com.asiainfo.crm.so.exe.ws.crmcallams.imswrapservice.SQueryPayInfoReq req) throws java.rmi.RemoteException;
}
