/**
 * IImsWrapQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.inter.exe.webservice.client.imswrapservice;

public interface IImsWrapQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryReguideInfoResp do_queryReguideInfo(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryReguideReq queryReguideReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryTransactionfeeResp doQueryTransactionFee(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryTransactionFeeReq queryTransactionFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryCapMaxResponse do_queryCapMax(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryCapMaxReq sQueryCapMaxReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryNotifyHisResponse doQueryNotifyHis(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryNotificationHisReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.Billinfo[] do_queryBillExt(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryBillExt sQueryBillExtReq) throws java.rmi.RemoteException;
    public void do_clearDbAndMdbData(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.ClearDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryAllowanceResponse doQueryAllowance(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAllowanceReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAgentBalanceResponse doQueryAgentBalance(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAgentBalanceReq doQueryAgentBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAutoTopUpResponse do_queryAutoTopUp(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryAutoTopUpReq queryAutoTopUpReq, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryMainPhoneByAcctIdResponse do_queryMainPhoneByAcctId(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryMainPhoneByAcctIdReq queryMainPhoneByAcctIdReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryBillExResponse doQueryBillEx(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QryBillForOSEInReq qryBillForOSEInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryWorkLogResponse doQueryWorkLog(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryWorkLogReq queryWorkLogReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoSMngQueryDepositResponse doQueryDeposit(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SMngQueryDepositReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryInvoiceAttributeResponse doQueryInvoiceAttribute(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryInvoiceAttributeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryCDRResponse doQueryCDR(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryCDRReq sQueryCDRReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryResponse doQuery(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryType[] queryTypeList, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryAccountInfoResponse do_QueryAccountInfo(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryType[] queryTypeList, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryAccountInfoParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryTermBalanceResponse doQueryTermBalance(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.TermQueryParam termQueryParam, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.GetDebitDataResponse doQueryDebitData(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.GetDebitDataRequest req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryNtCdrResponse do_queryNtCdr(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryNtCdrReq sQueryNtCdrReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryMdbDataResponse do_queryAbmData(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryAbmDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryOrderInfoResponse doQueryOrderInfo(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryOrderInfoReq doqueryOrderInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAcctDetailByCustResponse doQueryAcctDetailByCust(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAcctDetailByCustReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoGetCaInvIndexResponse doGetCaInvIndex(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SgetCaInvIndexReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryBillingStatusResponse do_queryBillingStatus(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQryBillStsReq qryBillStsReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryProductChargeResponse doQueryProductCharge(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQryProdChargeIn[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryLedgerResponse doQueryLedger(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryledgerInReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryMdbDataResponse do_queryMdbData(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryMdbDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryInstallmenInfoResponse doQueryInstallmentInfo(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryInstallmentInfoReq SQueryInstallmentInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.BillAmountResponse doQueryBillAmount(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.QueryBillAmountParam queryBillAmountParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAgentDepositResponse doQueryAgentDeposit(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryAgentDepositReq doQueryAgentDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryGraphResponse do_queryGraph(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryGraphReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryPointInfoResponse doQueryPoint(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQryPointInfoReq SQryPointInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryTaxResponse doQueryTax(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryTaxReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryRecurringfeeOnetimefeeResp doQueryRecurringAndOnetimeFee(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryRecurringAndOnetimeFeeReq queryRecurringFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryLostBalanceResponce do_queryLostBalance(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryLostBalanceReq queryLostBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryInvoiceInfoResponse do_queryInvoiceInfo(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryInvoiceInfoReq sQueryInvoiceInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.DoQueryPayInfoResponse doQueryPayInfo(com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.RequestHead requestHead, com.asiainfo.crm.inter.exe.webservice.client.imswrapservice.SQueryPayInfoReq req) throws java.rmi.RemoteException;
}
