/**
 * IImsServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.cm.dk.ws.imsservice;

public interface IImsServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangePbsManualStatusResponse doChangePbsManualStatus(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, java.lang.Long acctId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.UpdatePayChannelResponse updatePayChannel(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.UpdatePayChannelReq payChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoCaRelationUserResponse do_caRelationUser(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ScaRelateUserReq sCARelationUserReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoSplitResponse do_split(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SUserPaySplitRel[] relationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoCreditNotifyMgntResponse doManageNotifyFlag(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SCreditNotifyMgntReq sCreditNotifyMgntReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoSetExemptCreditLimitResponse doSetExemptCreditLimit(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SSetEmptLimitReq setExemptLimitReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoDeactivateGroupResponse do_deactivateGroup(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SDeactivateGroupReq sDeactivateGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoSetNotificationFlagResponse doSetNotificationFlag(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SSetNotificationFlagReq ssetNotificationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoCancelProductAuthResponse doCancelProductAuth(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.DoCancelProductAuthReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoMgntGroupMemberResponse do_mgntGroupMember(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SMgnGroupMemberReq sMngGroupMemberReq, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeGroupResponse do_changeGroup(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SGroup sGroup) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoCaRelationResponse do_caRelation(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ScaRelateReq sCARelationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoModifyUserBasicInfoResponse do_modifyUserBasicInfo(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SUser sUser) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeBillCycleResponse do_changeBillCycle(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SChgBillCycleReq sChgBillCycleReq, com.asiainfo.crm.cm.dk.ws.imsservice.SBillCycle old_bill_cycle, com.asiainfo.crm.cm.dk.ws.imsservice.SBillCycle new_bill_cycle, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeProductResponse do_changeMainPromotion(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SChangeProduct sChgProduct, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeUserLanguageResponse do_changeUserLanguage(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ChangeUserLanguageReq changeUserLanguageReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoManageIRPartyResponse do_manageIRParty(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SManagerIRPartyReq sManageIRParty) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoMgntCRMBlackListResponse do_mgntCRMBlackList(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SMgntCRMBlackListReq smgntCRMBlackListReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoMgntCallScreenResponse do_mgntCallScreen(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SMgntCallScreenReq sCallScreenReq, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoMgntScpProfileResponse do_mgntScpProfile(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ScpProfileInfo scpProfileInfo, com.asiainfo.crm.cm.dk.ws.imsservice.SUserAuth sUserAuth, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoRemoveUserResponse do_removeUser(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SRemoveReq sRemove, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoSetConsumptionResponse doSetConsumption(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SSetConsumptionReq sSetBudget) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoBankConfigurationResponse do_bankConfiguration(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.BankInfo bankInfo, java.lang.Short oper_type) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoManageUserFriendsNumsResponse do_manageUserFriendsNums(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ManageUserFriendsNum sMangeUserFNs, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoResetNegativeValueResponse do_resetNegativeValue(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SResetNegativeValueReq resetNegativeValueReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoModifyProductStateResponse do_modifyProductState(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ModifyProductState sChangeInfo, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee sOneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoDeletePrematchResponse do_deletePrematch(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SDeletePrematchReq sDeletePrematchReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoNewRegistrationResponse doNewRegistration(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.NewRegistration newRegistration, java.lang.Short flag, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoDeactivateGroupMemResponse do_deactivateGroupMem(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SDeactivateGroupMemReq sDeactivateGroupMemReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoSetMaxFreeResourceResponse doSetMaxFreeResource(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.MaxFreeResourceReq maxFreeResourceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoProductAuthResponse doProductAuth(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.DoProductAuthReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoNumberPortabilityResponse doNumberPortability(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.MnpReq[] mnpList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.ChgGroupProductResp do_changeGroupProducts(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ChgGroupProduct sChangeInfo, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangePaymentModeResponse do_changePaymentMode(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SChangePaymentModeReq sChangePaymentMode, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoNetaxeptRegisterResponse doNetaxeptRegister(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.DoNetaxeptRegisterReq doNetaxeptRegisterReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoDeleteGroupResponse do_deleteGroup(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SDeleteGroupReq sDeleteGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeOwnerReqResponse do_changeOwnerReq(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SChangeOwnerReq sChangeOwner, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoDismissReqResponse do_dismissReq(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SDismissReq sDismissReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoNPRangeSyncResponse doNPRangeSync(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.NpRangeInfo[] doNPRangeSyncReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoReguideMgntResponse do_reguide(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SUserPayReguideRel[] sRelationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoRenewRegistrationResponse do_renewRegistration(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.RenewRegistration sRenew) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeMsisdnAndSimResponse do_changeMsisdnAndSim(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ChangeMsisdnAndSimInfo changeInfo, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoFirstActivationResponse do_firstActivation(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SFristActiveReq sFristActiveReq, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoNewGroupReqResponse do_newGroupReq(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SNewGroupReq sNewGroupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoOrderProductAuthResponse doOrderProductAuth(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.DoOrderProductAuthReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoModifyAccountBasicInfoResponse doModifyAccountBasicInfo(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SAccount sAccount, com.asiainfo.crm.cm.dk.ws.imsservice.SContactOper[] sContactOperList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoOperateMultiSimResponse do_manageMultiSim(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SOperateMultiSimReq sOperateMultiSimReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoModifyCustBasicInfoResponse do_modifyCustBasicInfo(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SCustomer sCustomer, com.asiainfo.crm.cm.dk.ws.imsservice.SContactOper[] sContactOperList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoLifeCycleMgntResponse doOnHold(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SUserStatus sLifeCycle, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoAuthParentResponse do_authParent(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SAuthParentReq sAuthReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoManagePayChannelResponse doManagePayChannel(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.ManagePayChannelReq managePayChannelReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoSetBudgetResponse doSetBudget(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SSetBudgetReq sSetBudget) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoPBXNumberRangeSyncResponse doPBXNumberRangeSync(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.PbxNumberRange[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoLifeCycleMgntResponse doLifeCycleMgnt(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SUserStatus sLifeCycle, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public void do_UpdateBillingAddressInfo(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SBillingAddressInfo billingAddressInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeGroupInfoResponse do_changeGroupInfo(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SChangeGroupInfoReq changeGroupInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoVPNGroupRelationResponse do_vpnGroupRelation(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SvpnRelationReq SVPNRelationReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imsservice.DoChangeProductResponse do_changeProduct(com.asiainfo.crm.cm.dk.ws.imsservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imsservice.SChangeProduct sChgProduct, com.asiainfo.crm.cm.dk.ws.imsservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
}
