package com.asiainfo.crm.cm.customer.speusermain.ivalues;
import com.ai.appframe2.common.DataStructInterface;
import java.sql.Timestamp;
public interface IBOCmUserSpeuserMainValue extends DataStructInterface{
  public final static String S_SpeuserId ="SPEUSER_ID";
  public final static String S_PhoneId ="PHONE_ID";
  public final static String S_AcctId ="ACCT_ID";
  public final static String S_CreditLevel ="CREDIT_LEVEL";
  public final static String S_State ="STATE";
  public final static String S_CreateOpId ="CREATE_OP_ID";
  public final static String S_CreateOrgId ="CREATE_ORG_ID";
  public final static String S_OpId ="OP_ID";
  public final static String S_OrgId ="ORG_ID";
  public final static String S_DoneCode ="DONE_CODE";
  public final static String S_CreateDate ="CREATE_DATE";
  public final static String S_DoneDate ="DONE_DATE";
  public final static String S_EffectiveDate ="EFFECTIVE_DATE";
  public final static String S_ExpireDate ="EXPIRE_DATE";
  public final static String S_RegionId ="REGION_ID";
  public final static String S_Remarks ="REMARKS";
  public  long getSpeuserId();
  public  long getPhoneId();
  public  long getAcctId();
  public  long getCreditLevel();
  public  String getState();
  public  long getCreateOpId();
  public  long getCreateOrgId();
  public  long getOpId();
  public  long getOrgId();
  public  long getDoneCode();
  public  Timestamp getCreateDate();
  public  Timestamp getDoneDate();
  public  Timestamp getEffectiveDate();
  public  Timestamp getExpireDate();
  public  String getRegionId();
  public  String getRemarks();
  public void setSpeuserId(long value);
  public void setPhoneId(long value);
  public void setAcctId(long value);
  public void setCreditLevel(long value);
  public void setState(String value);
  public void setCreateOpId(long value);
  public void setCreateOrgId(long value);
  public void setOpId(long value);
  public void setOrgId(long value);
  public void setDoneCode(long value);
  public void setCreateDate(Timestamp value);
  public void setDoneDate(Timestamp value);
  public void setEffectiveDate(Timestamp value);
  public void setExpireDate(Timestamp value);
  public void setRegionId(String value);
  public void setRemarks(String value);
}
