/**
 * IImsWrapQueryServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.cm.dk.ws.imswrapqueryservice;

public interface IImsWrapQueryServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryAllowanceResponse doQueryAllowance(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAllowanceReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryTemplateResponse doQueryTemplate(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryTemplateReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryInvoiceAttributeResponse doQueryInvoiceAttribute(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryInvoiceAttributeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryReguideInfoResp do_queryReguideInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryReguideReq queryReguideReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAllowanceDtlResp doQueryAllowanceDtls(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAllowanceDtlReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryCDRSumResponse doQueryCDRSum(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryCDRSumReq sQueryCDRSumReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryThrottledResp doQueryThrottled(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryThrottledReq sQueryThrottledReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryInvoiceInfoResponse do_queryInvoiceInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryInvoiceInfoReq sQueryInvoiceInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryInstallmenInfoResponse doQueryInstallmentInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryInstallmentInfoReq SQueryInstallmentInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryTransactionfeeResp doQueryTransactionFee(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryTransactionFeeReq queryTransactionFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryAcctInfoForPayResponse doQueryAcctInfoForPay(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryAcctInfoForPayReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryOrderInfoResponse doQueryOrderInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryOrderInfoReq doqueryOrderInfoReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.Billinfo[] do_queryBillExt(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryBillExt sQueryBillExtReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryBillingStatusResponse do_queryBillingStatus(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQryBillStsReq qryBillStsReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryMainPhoneByAcctIdResponse do_queryMainPhoneByAcctId(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryMainPhoneByAcctIdReq queryMainPhoneByAcctIdReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryMdbDataResponse do_queryAbmData(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryAbmDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAcctDetailByCustResponse doQueryAcctDetailByCust(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAcctDetailByCustReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryWorkLogResponse doQueryWorkLog(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryWorkLogReq queryWorkLogReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryGraphResponse do_queryGraph(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryGraphReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryBillExResponse doQueryBillEx(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QryBillForOSEInReq qryBillForOSEInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryProductChargeResponse doQueryProductCharge(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQryProdChargeIn[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAgentBalanceResponse doQueryAgentBalance(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAgentBalanceReq doQueryAgentBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.GetDebitDataResponse doQueryDebitData(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.GetDebitDataRequest req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.BillAmountResponse doQueryBillAmount(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryBillAmountParam queryBillAmountParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryTermBalanceResponse doQueryTermBalance(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.TermQueryParam termQueryParam, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoGetCaInvIndexResponse doGetCaInvIndex(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SgetCaInvIndexReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoSMngQueryDepositResponse doQueryDeposit(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SMngQueryDepositReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryCapMaxResponse do_queryCapMax(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryCapMaxReq sQueryCapMaxReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryLostBalanceResponce do_queryLostBalance(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryLostBalanceReq queryLostBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryPayInfoResponse doQueryPayInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryPayInfoReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAgentDepositResponse doQueryAgentDeposit(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAgentDepositReq doQueryAgentDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryRegretDeductInfoResponse doQueryRegretDeductInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryRegretInfo queryRegretInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryNotifyHisResponse doQueryNotifyHis(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryNotificationHisReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryNtCdrResponse do_queryNtCdr(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryNtCdrReq sQueryNtCdrReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryRecurringfeeOnetimefeeResp doQueryRecurringAndOnetimeFee(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryRecurringAndOnetimeFeeReq queryRecurringFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryRegretStsResponse doQueryRegretSts(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryRegretInfo queryRegretInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryCDRBusiResp doNewQueryCDRBusi(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryCDRBusiReq sQueryCDRBusiReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAcctStatusmentResp doQueryAccountStatement(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAcctStatusmentReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryResponse doQuery(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryType[] queryTypeList, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAutoTopUpResponse do_queryAutoTopUp(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryAutoTopUpReq queryAutoTopUpReq, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public void do_clearDbAndMdbData(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.ClearDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryCDRResponse doQueryCDR(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryCDRReq sQueryCDRReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryLedgerResponse doQueryLedger(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryledgerInReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAmountResp doQueryAmount(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryAmountReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryDeductCondResponse doQueryDeductCond(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryDeductCondRequest req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryTaxResponse doQueryTax(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryTaxReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryBillXmlResponse doQueryBillXml(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryBillXmlReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.STransferTransformRuleResponse doQueryTransferTransformRule(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.STransferTransformRuleReq requestBody) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryCDRFileResponse doQueryCDRFile(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryCDRReq sQueryCDRReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryAccountInfoResponse do_QueryAccountInfo(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.QueryType[] queryTypeList, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryAccountInfoParam queryParam) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryMdbDataResponse do_queryMdbData(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQueryMdbDataReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.DoQueryPointInfoResponse doQueryPoint(com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapqueryservice.SQryPointInfoReq SQryPointInfoReq) throws java.rmi.RemoteException;
}
