/**
 * IImsWrapServiceWs.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.crm.cm.dk.ws.imswrapservice;

public interface IImsWrapServiceWs extends java.rmi.Remote {
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoRegretRefundResponse doRegretRefund(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SRegretRefundReq sRegretRefundReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoEtopupResponse do_etopup(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.EtopupReq etopupReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.SAdjustFinesResp doAdjustFines(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SAdjustFinesReq sAdjustFinesReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdjustBillResponse doAdjustBill(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, java.lang.Short adjustType, com.asiainfo.crm.cm.dk.ws.imswrapservice.Billinfo billInfo, java.lang.Short notificationFlag) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAutoTopUpResponse doAutoTopUp(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SAutoTopUpReq autoTopUpReq, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoMailGroupManageResponse do_mailGroupManage(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SMailGroupManageReq mailGroupManageReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelOrderResponse doCancelOrder(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelOrderReq doCancelOrderReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoDeductPointsResponse do_deductPoints(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SDeductPointsReq sDeductPointsReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAgentDepositResponse doAgentDeposit(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAgentDepositReq do_agentDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoRefundRemainBalanceResponse doRefundRemainBalance(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.RefundParam refundParam, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public void doCreditLimit(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SCreditLimitInReq sCreditLimitIn) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInsertPrtRecResponse doInsertPrtRec(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SPrintIn[] printRecReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoUionChargeReplyResponse doUionChargeReply(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.UionChargeReplyReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInstallmentPrePayResponse doInstallmentPrePay(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.InstallmentPrePay[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdjustBetweenAcctResponse doAdjustBetweenAcct(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdjBetweenAcctInReq doAdjBetweenAcctInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoOneTimeFeeResponse do_oneTimeFeeDelayCharge(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee[] oneTimeFeeList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoHotBillResponse doHotBill(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SHotBillReq sHotBillReq, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoQueryPayDataResponse doQueryPayData(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.PrintInReq printInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelInstalPrePayResponse doCancelInstalPrePay(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelInstalPrePayReq doCancelInstalPrePayReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.UpdateOrderUserIdResp doUpdateOrderUserId(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.OrderUserInfo orderUserInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoQueryUnOrderFeeResponse doQueryUnOrderFee(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.QueryUnOrderFeeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAcceptInstalResponse doAcceptInstal(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAcceptInstalReq doAcceptInstalReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdvancePaymentResponse do_advancePayment(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AdvancePaymentReq advancePaymentReq, java.lang.Short notification_flag) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoTransferResponse doTransfer(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.STransferReq sTransferReq, java.lang.Short notificationFlag, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInstanceAllowanceResponse doInstanceAllowance(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SAllowanceUsage[] req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.AdjustMultiBillResponse doAdjustMultiBill(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AdjustMultiBillInReq adjustMultiBillInReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoGsmTopUpResponse do_gsmTopUp(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SGsmTopUpReq gsmTopUp) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoOneTimeFeeResponse doOneTimeFee(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee[] oneTimeFeeList) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoSMngDepositResponse doManageDeposit(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SMngDepositReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAutoTopUpOnDemondResponse do_autoTopUpOnDemond(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AutoTopUpOnDemondReq autoTopUpOnDemondReq, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public void doRePaymentFtp(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, java.lang.Long seqId) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoSetCreditLimitResponse doSetCreditLimit(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SSetCreditLimitReq SSetCreditLimit) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoSetNegativeBalanceResponse doSetNegativeBalance(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SSetNegativeBalanceReq ssetNegativeBalanceReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoTopUpByCashResponse doTopUpByCash(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.STopUpInfo sTopUpInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdTransferAssetResponse doAdTransferAsset(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AdTransferParam transferParam, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInsertOrderInfoResponse doInsertOrderInfo(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SOrderInfo req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelPaymentResponse doCancelPayment(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.CancelPaymentInfo cancelPaymentInfo) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCheckDepositAmountResponse doCheckDepositAmount(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.CheckDepositAmountReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInstalMoveResponse doInstalMove(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInstalMoveReq doInstalMoveReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdjustPointResponse doAdjustPoint(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AdjustPointReq adjustPointReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoDealApproveResponseResponse doDealApproveResponse(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoDealApproveResponseReq doDealApproveResponseReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelInstalmentResponse doCancelInstalment(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SCancelInstalmentReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelOneTimeFeeResponse doCancelOneTimeFee(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SCancelOneTimeFeeReq sCancelOneTimeFeeReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoPaymentAndBillAdjustResponse doPaymentAndBillAdjust(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SPaymentReq spaymentReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoLetterDataResponse doLetterData(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoLetterDataReq doLetterDataReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoUnifiedPayResponse doUnifiedPay(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoUnifiedPayReq doUnifiedPayReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAdjustBalanceResponse doAdjustBalance(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AdjustBalanceReq adjustReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAutoTopUpResponse do_autoTopUp4GUI(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.AutoTopUpReq autoTopUpReq, com.asiainfo.crm.cm.dk.ws.imswrapservice.OneTimeFee oneTimeFee) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoRejectDirectDebitResponse doRejectDirectDebit(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SRejectDDReq sRejectDDReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelTopUpResponse doCancelTopUp(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SCancelTopUpReq scancelTopUp) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoCancelGsmTopUpResponse do_cancelGsmTopUp(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SCancelGsmTopUpReq gsmTopUp) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInstalContractResponse doContractInstal(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SDoInstalContractReq doInstalContract) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoUionChargeRespone doUionCharge(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.UionChargeReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoRollbackPaymentResponse doRollbackPayment(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SReceiptInfoReq req) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAgentSelfDepositRespone doAgentSelfDeposit(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.DoAgentSelfDepositReq do_agentSelfDepositReq) throws java.rmi.RemoteException;
    public com.asiainfo.crm.cm.dk.ws.imswrapservice.DoInstalChangeResponse doInstalChange(com.asiainfo.crm.cm.dk.ws.imswrapservice.RequestHead requestHead, com.asiainfo.crm.cm.dk.ws.imswrapservice.SInstalChangeReq req) throws java.rmi.RemoteException;
}
